### ISSUE TITLE
Remove hover and custom classes for colors

### ISSUE THREAD

**Issue by amrap030** [imfaber/vue-tasty-burgers#16]
Is there a way to remove the hover colors (for now it is lightening the actual color) and is there a way to add your own classes that specify the colors, for example with tailwind css classes? Or maybe in a css file?

**Comment by imfaber** [comment]
Hi @amrap030 

I'm planning to add a couple of props to control hover and focus colors but at the moment the only way to remove the hover effect is via CSS.

#### Disable hover
```css
.hamburger:hover {
    opacity: 1 !important;
}
```

#### Customize hover colors
In order to use a different colors you need to style the inner elements.

```css
..hamburger:hover .hamburger-box * {
    background-color: red !important;
}
```

You need `!important` unless you use a stronger selector.

Hope this helps.
